389. Find the Difference  QuestionEditorial Solution  My Submissions
Total Accepted: 9865 Total Submissions: 19787 Difficulty: Easy
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Output:
e

Explanation:
'e' is the letter that was added.
Subscribe to see which companies asked this question

Hide Tags Hash Table Bit Manipulation
Hide Similar Problems (E) Single Number

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> mp(256);
        for (auto c:s) mp[c]++;
        for (auto c:t) {
            mp[c]--;
            if (mp[c]<0) return c;
        }
        return 0;
    }
};

2. Bit manipulation
class Solution {
public:
    char findTheDifference(string s, string t) {
        char res=0;
        for (auto c:s) res^=c;
        for (auto c:t) res^=c;
        return res;
    }
};

